spring:

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: exchange
    password: exchange

  profiles:
    active: develop

  jpa:
    hibernate:
      ddl-auto: validate

  web:
    resources:
      static-locations: classpath:/public/

  thymeleaf:
    cache: false
    prefix: classpath:/public/
#    suffix: html


logging:
  level:
    web: debug

