spring:

  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: exchange
    password: exchange

  profiles:
    active: develop

  jpa:
    hibernate:
      ddl-auto: validate


  thymeleaf:
    cache: false
    prefix: classpath:/public/
#    suffix: html


logging:
  level:
    web: debug

